// apps/react/src/App.jsx
import React from 'react';
import ErrorBoundary from './components/ErrorBoundary';
import SearchForm from './components/SearchForm';
import LoadingState from './components/LoadingState';
import ErrorState from './components/ErrorState';
import WeatherContent from './components/WeatherContent';
import useWeatherData from './hooks/useWeatherData';

function App() {
  const { weatherData, isLoading, error, loadWeather } = useWeatherData();

  const handleSearch = async(city) => {
    await loadWeather(city);
  };

  return (
    <ErrorBoundary>
      <header className="header">
        <div className="container">
          <h1 className="header__title">Weather Front</h1>
        </div>
      </header>

      <main className="main">
        <div className="container">
          <SearchForm
            onSearch={handleSearch}
            isLoading={isLoading}
          />

          <div className="weather-container" data-testid="weather-container">
            <LoadingState isVisible={isLoading} />
            <ErrorState isVisible={!!error && !isLoading} message={error} />
            <WeatherContent isVisible={!!weatherData && !isLoading && !error} weatherData={weatherData} />
          </div>
        </div>
      </main>

      <footer className="footer">
        <div className="container">
          <p className="footer__text">
            Built with React • MIT License •
            <a href="https://github.com/Lissy93" className="footer__link" target="_blank" rel="noopener">
              Alicia Sykes
            </a>
          </p>
        </div>
      </footer>
    </ErrorBoundary>
  );
}

export default App;

// apps/vue/src/App.vue
<template>
  <header class="header">
    <div class="container">
      <h1 class="header__title">Weather Front</h1>
    </div>
  </header>

  <main class="main">
    <div class="container">
      <SearchForm 
        @search="searchWeather" 
        :is-loading="isLoading"
        :current-value="searchValue"
      />
      
      <div class="weather-container" data-testid="weather-container">
        <LoadingState v-if="isLoading" />
        
        <ErrorState 
          v-if="error && !isLoading" 
          :message="error" 
        />
        
        <WeatherContent 
          v-if="weatherData && !isLoading && !error" 
          :weather-data="weatherData" 
        />
      </div>
    </div>
  </main>

  <footer class="footer">
    <div class="container">
      <p class="footer__text">
        Built with Vue 3 • MIT License • 
        <a href="https://github.com/Lissy93" class="footer__link" target="_blank" rel="noopener">Alicia Sykes</a>
      </p>
    </div>
  </footer>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import SearchForm from './components/SearchForm.vue'
import LoadingState from './components/LoadingState.vue'
import ErrorState from './components/ErrorState.vue'
import WeatherContent from './components/WeatherContent.vue'
import { weatherService } from './services/weatherService.js'

const weatherData = ref(null)
const isLoading = ref(false)
const error = ref(null)
const searchValue = ref('London')

const searchWeather = async (city) => {
  isLoading.value = true
  error.value = null
  
  try {
    const data = await weatherService.getWeatherByCity(city)
    weatherData.value = data
    searchValue.value = city
    
    // Save to localStorage
    try {
      localStorage.setItem('weather-app-location', city)
    } catch (e) {
      // Ignore localStorage errors
    }
  } catch (err) {
    error.value = err.message || 'Failed to fetch weather data'
    weatherData.value = null
  } finally {
    isLoading.value = false
  }
}

onMounted(async () => {
  let initialCity = 'London'
  
  // Try to get saved location from localStorage
  try {
    const savedLocation = localStorage.getItem('weather-app-location')
    if (savedLocation) {
      initialCity = savedLocation
    }
  } catch (e) {
    // Ignore localStorage errors
  }
  
  await searchWeather(initialCity)
})
</script>
