// apps/angular/src/app/components/error-state.component.ts
import { Component, input } from '@angular/core';

@Component({
  selector: 'app-error-state',
  template: `
    <div
      class="error"
      data-testid="error"
      [hidden]="!isVisible()"
    >
      <h2 class="error__title">Unable to load weather data</h2>
      <p class="error__message">
        {{ message() || 'Please check the city name and try again.' }}
      </p>
    </div>
  `
})
export class ErrorStateComponent {
  readonly isVisible = input(false);
  readonly message = input<string | null>(null);
}

// apps/react/src/components/ErrorState.jsx
import React from 'react';

const ErrorState = ({ isVisible, message }) => {
  return (
    <div
      className="error"
      data-testid="error"
      hidden={!isVisible}
    >
      <h2 className="error__title">Unable to load weather data</h2>
      <p className="error__message">
        {message || 'Please check the city name and try again.'}
      </p>
    </div>
  );
};

export default React.memo(ErrorState);
