// apps/qwik/src/components/ErrorState.tsx
import { component$ } from '@builder.io/qwik';

interface ErrorStateProps {
  message: string;
}

export const ErrorState = component$<ErrorStateProps>(({ message }) => {
  return (
    <div class="error" data-testid="error">
      <h2 class="error__title">Unable to fetch weather data</h2>
      <p class="error__message">{message}</p>
    </div>
  );
});

// apps/react/src/components/ErrorState.jsx
import React from 'react';

const ErrorState = ({ isVisible, message }) => {
  return (
    <div
      className="error"
      data-testid="error"
      hidden={!isVisible}
    >
      <h2 className="error__title">Unable to load weather data</h2>
      <p className="error__message">
        {message || 'Please check the city name and try again.'}
      </p>
    </div>
  );
};

export default React.memo(ErrorState);
