// apps/solid/src/components/LoadingState.jsx
import { Show } from 'solid-js';

function LoadingState(props) {
  return (
    <Show when={props.isVisible}>
      <div class="loading" data-testid="loading">
        <div class="loading__spinner"></div>
        <p>Loading weather data...</p>
      </div>
    </Show>
  );
}

export default LoadingState;

// apps/react/src/components/LoadingState.jsx
import React from 'react';

const LoadingState = ({ isVisible }) => {
  return (
    <div
      className="loading"
      data-testid="loading"
      hidden={!isVisible}
    >
      <div className="loading__spinner"></div>
      <p>Loading weather data...</p>
    </div>
  );
};

export default React.memo(LoadingState);
