// apps/solid/src/components/WeatherContent.jsx
import { Show } from 'solid-js';
import CurrentWeather from './CurrentWeather';
import Forecast from './Forecast';

function WeatherContent(props) {
  return (
    <Show when={props.isVisible}>
      <div class="weather-content" data-testid="weather-content">
        <div class="weather-layout">
          <CurrentWeather weatherData={props.weatherData} />
          <Forecast weatherData={props.weatherData} />
        </div>
      </div>
    </Show>
  );
}

export default WeatherContent;

// apps/react/src/components/WeatherContent.jsx
import React from 'react';
import CurrentWeather from './CurrentWeather';
import Forecast from './Forecast';

const WeatherContent = ({ isVisible, weatherData }) => {
  return (
    <div
      className="weather-content"
      data-testid="weather-content"
      hidden={!isVisible}
    >
      <div className="weather-layout">
        <CurrentWeather weatherData={weatherData} />
        <Forecast weatherData={weatherData} />
      </div>
    </div>
  );
};

export default React.memo(WeatherContent);
