// apps/svelte/src/lib/components/Forecast.svelte
<script>
  import { tick } from 'svelte';
  import ForecastItem from './ForecastItem.svelte';

  export let weatherData = null;
  
  let activeForecastIndex = null;

  async function handleToggleForecast(event) {
    const index = event.detail;
    
    if (activeForecastIndex === index) {
      activeForecastIndex = null;
    } else {
      activeForecastIndex = index;
      
      // Smooth scroll to the expanded item
      await tick();
      setTimeout(() => {
        const activeElement = document.querySelector('.forecast-item.active');
        if (activeElement) {
          activeElement.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
        }
      }, 100);
    }
  }
</script>

{#if weatherData}
  <section class="forecast-section">
    <h2 class="section-title">7-Day Forecast</h2>
    <div class="forecast">
      <div class="forecast__list" data-testid="forecast-list">
        {#each weatherData.daily.time.slice(0, 7) as date, index}
          <ForecastItem
            daily={weatherData.daily}
            {index}
            isActive={activeForecastIndex === index}
            on:toggle={handleToggleForecast}
          />
        {/each}
      </div>
    </div>
  </section>
{/if}

// apps/solid/src/components/Forecast.jsx
import { createSignal, Show, For } from 'solid-js';
import ForecastItem from './ForecastItem';

function Forecast(props) {
  const [activeForecastIndex, setActiveForecastIndex] = createSignal(null);

  const handleToggleForecast = (index) => {
    if (activeForecastIndex() === index) {
      setActiveForecastIndex(null);
    } else {
      setActiveForecastIndex(index);

      // Smooth scroll to the expanded item
      setTimeout(() => {
        const activeElement = document.querySelector('.forecast-item.active');
        if (activeElement) {
          activeElement.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
        }
      }, 100);
    }
  };

  return (
    <Show when={props.weatherData}>
      <section class="forecast-section">
        <h2 class="section-title">7-Day Forecast</h2>
        <div class="forecast">
          <div class="forecast__list" data-testid="forecast-list">
            <For each={props.weatherData.daily.time.slice(0, 7)}>
              {(date, index) => (
                <ForecastItem
                  daily={props.weatherData.daily}
                  index={index()}
                  isActive={activeForecastIndex() === index()}
                  onToggle={handleToggleForecast}
                />
              )}
            </For>
          </div>
        </div>
      </section>
    </Show>
  );
}

export default Forecast;
