// apps/vue/src/components/WeatherContent.vue
<template>
  <div class="weather-content" data-testid="weather-content">
    <div class="weather-layout">
      <CurrentWeather :weather-data="weatherData" />
      <Forecast :weather-data="weatherData" />
    </div>
  </div>
</template>

<script setup>
import CurrentWeather from './CurrentWeather.vue'
import Forecast from './Forecast.vue'

defineProps({
  weatherData: {
    type: Object,
    required: true
  }
})
</script>

// apps/svelte/src/lib/components/WeatherContent.svelte
<script>
  import CurrentWeather from './CurrentWeather.svelte';
  import Forecast from './Forecast.svelte';

  export let isVisible = false;
  export let weatherData = null;
</script>

<div 
  class="weather-content" 
  data-testid="weather-content" 
  hidden={!isVisible}
>
  <div class="weather-layout">
    <CurrentWeather {weatherData} />
    <Forecast {weatherData} />
  </div>
</div>
