// apps/react/src/components/WeatherContent.jsx
import React from 'react';
import CurrentWeather from './CurrentWeather';
import Forecast from './Forecast';

const WeatherContent = ({ isVisible, weatherData }) => {
  return (
    <div
      className="weather-content"
      data-testid="weather-content"
      hidden={!isVisible}
    >
      <div className="weather-layout">
        <CurrentWeather weatherData={weatherData} />
        <Forecast weatherData={weatherData} />
      </div>
    </div>
  );
};

export default React.memo(WeatherContent);

// apps/svelte/src/lib/components/WeatherContent.svelte
<script>
  import CurrentWeather from './CurrentWeather.svelte';
  import Forecast from './Forecast.svelte';

  export let isVisible = false;
  export let weatherData = null;
</script>

<div 
  class="weather-content" 
  data-testid="weather-content" 
  hidden={!isVisible}
>
  <div class="weather-layout">
    <CurrentWeather {weatherData} />
    <Forecast {weatherData} />
  </div>
</div>
